name: Monitor SIZO-11 slots

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/7 * * * *"

concurrency:
  group: monitor-sizo11
  cancel-in-progress: true

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install Chrome
          id: chrome
          uses: browser-actions/setup-chrome@v1
          with:
            chrome-version: stable   # можно и 140, но stable тоже ок
      
      - name: Export Chrome path
          run: echo "CHROME_PATH=${{ steps.chrome.outputs.chrome-path }}" >> $GITHUB_ENV


      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor (single check)
        id: run
        shell: bash
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          F_OKNO_EMAIL: ${{ secrets.F_OKNO_EMAIL }}
          F_OKNO_PASSWORD: ${{ secrets.F_OKNO_PASSWORD }}
          TARGET_URL: https://f-okno.ru/base/moscovskaya_oblast/sizo11noginsk
          LOGIN_URL: https://f-okno.ru/login?request_uri=%2Fbase%2Fmoscovskaya_oblast%2Fsizo11noginsk
          CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
          ONLY_NOTIFY_WHEN_FREE: "1"
        run: |
          set -euo pipefail
          export PYTHONUNBUFFERED=1
          : > run.log
          python f_okno_monitor_selenium.py 2>&1 | tee -a run.log
          exit ${PIPESTATUS[0]}

      - name: Upload debug artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            run.log
            page.html
            page.png
